Strech/avrora

README.md, lib/avrora.ex, lib/avrora/encoder.ex, mix.exs, test/avrora/encoder_test.exs
* New method `Avrora.decode/1` with magic bytes agnostic approach
* Handling [OCF](https://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files) messages
* Updated roadmap
=> Add agnostic messages decoding

README.md
If you check the [official documentation](https://avro.apache.org/docs/1.8.2/spec.html), "Avro" is spelled that way.
=> AVRO -> Avro

.gitignore, lib/avrora.ex, lib/avrora/encoder.ex, lib/avrora/storage/registry.ex, mix.exs, test/avrora/encoder_test.exs
It will be possible to choose `format` style on encoding. Options will be:
* plain
* registry
* ocf
* guess (default)
Also, fixes supervision of the main module
=> Add optional format argumetn to encoding

lib/avrora/encoder.ex, lib/avrora/resolver.ex, mix.exs, test/avrora/encoder_test.exs, test/avrora/resolver_test.exs
Unfortunately, nightly programming is not that great on a quality side. I made a mistake by encoding and decoding schemas with registry magic thinking that a number after magic is a schema version, but the documentation explicitly said – schema id (i.e global schema id)
This PR will fix that mistake.
* Use `name:version` key when the schema is resolved by the registry
* Use `id` key when the schema is resolved by the registry (via global id)
* Use `name` key when the schema is resolved by the file name
=> Change resolver and memory storage rules

.travis.yml, README.md, config/config.exs, lib/avrora/config.ex, lib/avrora/encoder.ex, lib/avrora/resolver.ex, lib/avrora/storage.ex, lib/avrora/storage/memory.ex, lib/avrora/storage/registry.ex, mix.exs, test/avrora/encoder_test.exs, test/avrora/mapper_test.exs, test/avrora/resolver_test.exs, test/avrora/storage/memory_test.exs, test/support/mocks.ex, test/test_helper.exs
It's not flexible to cache schema resolved by the name with a key equal to its `name`. But it will drastically speed up the resolution process.
But behind the name without the version, we mind `latest`. Unfortunately, each schema update in the schema registry will update `latest` schema value. Let's cache it, but for a short period of time.
```elixir
config :avrora, names_cache_ttl: :timer.minutes(10)
```
=> Add names cache and its eviction

.dialyzer_ignore.exs, README.md, lib/avrora/encoder.ex, lib/avrora/resolver.ex, lib/avrora/schema.ex, lib/avrora/storage.ex, lib/avrora/storage/file.ex, lib/avrora/storage/memory.ex, lib/avrora/storage/registry.ex, test/avrora/encoder_test.exs, test/avrora/resolver_test.exs, test/avrora/schema_test.exs, test/avrora/storage/file_test.exs, test/avrora/storage/memory_test.exs, test/avrora/storage/registry_test.exs, test/fixtures/schemas/io/confluent/Messenger.avsc
When schema contains type reference by a name decoding will fail.
**TODO**
=> Fix schemas with types references

test/avrora/schema_test.exs
Just a typo that I've found reading the tests
=> Fix typo in schema_test

lib/avrora/schema/reference_collector.ex, test/avrora/schema/reference_collector_test.exs, test/fixtures/schemas/io/confluent/MailgunEvent.avsc
There is no need to capture the references via both return value and
accumulator. The old logic leads to exponential memory usage due to
repeated concatenation of same values again and again. Once the number
of fields in a schema crosses a threshold this leads to OOM
=> fix ReferenceCollector collect logic

.dialyzer_ignore.exs, lib/avrora.ex, lib/avrora/config.ex, lib/avrora/encoder.ex, lib/avrora/ets.ex, lib/avrora/resolver.ex, lib/avrora/schema.ex, lib/avrora/schema/name.ex, lib/avrora/storage.ex, lib/avrora/storage/file.ex, lib/avrora/storage/memory.ex, lib/avrora/storage/registry.ex, lib/avrora/test_case.ex, test/avrora/ets_test.exs, test/avrora/schema/name_test.exs, test/avrora/storage/memory_test.exs, test/test_helper.exs
This PR include 3 major changes:
1. `Avrora.Name` module was moved to `Avrora.Schema.Name`
2. `Avrora.TestCase` helper module gets `cleanup_storage!/1` function to clean storage between tests
3. `Avrora.ETS` module now supervisioned together with `Avrora.Storage.Memory` and owns all ETS tables generated by `Avrora.Schema`
Resolves: #21
=> Fix broken ETS references

.travis.yml, README.md, config/config.exs, lib/avrora/config.ex, lib/avrora/resolver.ex, test/avrora/encoder_test.exs, test/avrora/resolver_test.exs
=> Fix schema evalution scenario

lib/avrora/storage/registry.ex, test/avrora/storage/registry_test.exs
This PR enables Avro schema parsing with new schema registry's schema references feature, introducing a dedicated lookup function for references got from CSR.
Changes in this PR comes from the discussion of the deprecated #49  pull request.
cc @Strech
=> Managing schema registry's schema references

lib/avrora.ex, lib/avrora/encoder.ex, test/avrora/encoder_test.exs, test/integration/lib/interfaces.ex
This fixes a bug where decoding fails for a data that was encoded with a supplied `schema_name` and `:plain` format
If the encoded message starts with the magic byte (0x00) due to the data that was encoded, the wrong codec is selected by
https://github.com/Strech/avrora/blob/master/lib/avrora/encoder.ex#L76
when decoding it later. 
This causes the decoding to fail sporadically dependent on the encoded data. 
I propose to fix this by including an optional `format` argument to the `decode` function. 
Example: New test case that broke before adding the `format: plain` parameter
```shell
1) test when decoding plain message that starts with what looks like a magic byte (Avrora.EncoderTest)
test/avrora/encoder_test.exs:405
Assertion with == failed
code:  assert key == …
```
=> adds decode/3 with format option

lib/avrora/client.ex
You accidentally put `registry_url` as the return variable of the `registry_auth/0` function in this PR: https://github.com/Strech/avrora/pull/83/files#diff-d3c854ddf22006a09e725337d6c026d9cbe41454684022231fb56238a665047bR103
This is causing the error `** (CaseClauseError) no case clause matching:`
=> Fix registry_auth to return the proper variable

lib/mix/tasks/avrora.reg.schema.ex
Hello! I'm having troubles with `mix avrora.reg.schema` when I use the `--module` argument and my avrora client is configured with a `runtime.exs`.
I'll try to illustrate the problem, I have an avrora client like this one:
```elixir
defmodule MyApp.Avrora do
use Avrora.Client, otp_app: :my_app
end
```
and I'm using a `runtime.exs`
```elixir
import Config
config :my_app, MyApp.Avrora,
registry_url: System.fetch_env!("SCHEMA_REGISTRY_URL"),
registry_auth:
{:basic,
[
System.fetch_env!("SCHEMA_REGISTRY_USER"),
System.fetch_env!("SCHEMA_REGISTRY_PASS")
]}
```
now the problem is that `my_app` is not being loaded by `mix avrora.reg.schema --all --module MyApp.Avrora`, so I get the following:
```
schema `my.namespace.SomeEvent' will be skipped due to an error `unconfigured_registry_url'
```
due …
=> Load app config when `--module` arg is used

lib/avrora/encoder.ex, test/avrora/encoder_test.exs
The usual understanding, when a function accepts a keyword list as a last "options" argument, is that those options can be given in any order. On the other side, the current code pattern matches the list in exact order, so this expectation is not fulfilled, and this code raises a `FunctionClauseError`:
```ex
Avrora.encode(payload, format: :plain, schema_name: "io.confluent.Messenger")
```
This PR switches out the pattern matching on options, and uses appropriate `Keyword` functions to extract the values.
=> Allow encode/2 to receive opts in any order

.github/workflows/ci.yaml, config/config.exs, mix.exs, test/avrora/storage/file_test.exs, test/avrora/storage/registry_test.exs, test/support/avro_schema_store.ex
=> Measure :ets tables

lib/avrora/http_client.ex
Since elixir 1.17, using '' for a charlist produces a compile-time warning. Replacing them with ~c"" fixes the issue.
=> Use ~c"" for charlists to avoid warnings in recent elixir.

lib/avrora/client.ex, test/avrora/client_test.exs
This fixes an issue introduced in 0.29.0.
=> fix: check for nil before expanding path

lib/avrora/codec.ex, lib/avrora/codec/object_container_file.ex, lib/avrora/codec/plain.ex, lib/avrora/codec/schema_registry.ex, lib/avrora/encoder.ex, test/avrora/codec/object_container_file_test.exs, test/avrora/codec/plain_test.exs, test/avrora/codec/schema_registry_test.exs
Addressing https://github.com/Strech/avrora/issues/132
**Summary** 
- Deprecate is_decodable/1 and follow new naming convention  decodable?/1
- Log a warning message when `is_decodable/1` is used.
=> Change `is_decodable/1` to `decodable?/1`

lib/avrora/http_client.ex
**Addressing Bug that introduced in `0.29.0`** 
Issue:  https://github.com/Strech/avrora/issues/135
=> Patch/Fix: `Avrora.HTTPClient.post/3` to guard the map instead of binary ( No longer receiving binary payload)
